name: TypeScript Action
description: >-
  A GitHub Action written in TypeScript. Waits for a specified number of
  milliseconds and outputs the current time.
author: cashpilotthrive-hue
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: clock
  color: blue

# Define your inputs here.
inputs:
  milliseconds:
    description:
      The number of milliseconds to wait before setting the time output.
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: The time after the wait has completed.

runs:
  using: node24
  main: dist/index.js
